// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCveYn9dbpOltPwyaLR4pOvbRbNU6Kl7Ho',
    appId: '1:684482169381:web:bacfcad3439f48fd198dcc',
    messagingSenderId: '684482169381',
    projectId: 'test-bcf7d',
    authDomain: 'test-bcf7d.firebaseapp.com',
    storageBucket: 'test-bcf7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCroviL1gD0SU2TS7ZmueMs6seGceiVGFY',
    appId: '1:684482169381:android:ce78805a7db4b558198dcc',
    messagingSenderId: '684482169381',
    projectId: 'test-bcf7d',
    storageBucket: 'test-bcf7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy1V2IfWsttXznb03emJhLIBEArpn4ON4',
    appId: '1:684482169381:ios:5756b9ad6d47592a198dcc',
    messagingSenderId: '684482169381',
    projectId: 'test-bcf7d',
    storageBucket: 'test-bcf7d.appspot.com',
    iosBundleId: 'com.smriti.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy1V2IfWsttXznb03emJhLIBEArpn4ON4',
    appId: '1:684482169381:ios:b97ddd0a4b1d0de3198dcc',
    messagingSenderId: '684482169381',
    projectId: 'test-bcf7d',
    storageBucket: 'test-bcf7d.appspot.com',
    iosBundleId: 'com.example.test2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCveYn9dbpOltPwyaLR4pOvbRbNU6Kl7Ho',
    appId: '1:684482169381:web:12cc8061afa38f9c198dcc',
    messagingSenderId: '684482169381',
    projectId: 'test-bcf7d',
    authDomain: 'test-bcf7d.firebaseapp.com',
    storageBucket: 'test-bcf7d.appspot.com',
  );
}
